{
  parserClass="org.lvcargnini.systemverilog_language_plugin.parser.SystemVerilogParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
  parserUtilClass="org.lvcargnini.systemverilog_language_plugin.parser.SystemVerilogParserUtil"

  psiClassPrefix="SystemVerilog"
  psiImplClassSuffix="Impl"
  psiPackage="org.lvcargnini.systemverilog_language_plugin.psi"
  psiImplPackage="org.lvcargnini.systemverilog_language_plugin.psi.impl"

  elementTypeHolderClass="org.lvcargnini.systemverilog_language_plugin.psi.SystemVerilogTypes"
  elementTypeClass="org.lvcargnini.systemverilog_language_plugin.psi.SystemVerilogElementType"
  tokenTypeClass="org.lvcargnini.systemverilog_language_plugin.psi.SystemVerilogTokenType"

  psiImplUtilClass="org.lvcargnini.systemverilog_language_plugin.psi.impl.SystemVerilogPsiImplUtil"

}

svFile::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {mixin="org.lvcargnini.systemverilog_language_plugin.psi.impl.SystemVerilogNamedElementImpl"
  implements="org.lvcargnini.systemverilog_language_plugin.psi.SystemVerilogNamedElement" methods=[getKey getValue getName setName getNameIdentifier]}